import { chromium } from 'playwright';
const [, , url, out, w = '1440', h = '900', sel] = process.argv;
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: +w, height: +h }, deviceScaleFactor: 1, isMobile: +w < 700, hasTouch: +w < 700 });
const p = await ctx.newPage();
await p.goto('http://localhost:4321' + url, { waitUntil: 'networkidle' });
await p.evaluate(async () => { for (let y = 0; y < document.body.scrollHeight; y += 400) { window.scrollTo({ top: y, behavior: 'instant' }); await new Promise(r => setTimeout(r, 25)); } window.scrollTo({ top: 0, behavior: 'instant' }); });
await p.waitForTimeout(1200);
const t = sel ? await p.$(sel) : p;
await t.screenshot({ path: out, fullPage: !sel });
await b.close();
